### ISSUE TITLE
allowfullscreen not added to iframe

### ISSUE THREAD

**Issue by kubijo** [nimbis/djangocms-vimeo#5]
Hi,

I'd like to know your possible experience with issue of allowFullscreen attributes (webkitallowfullscreen mozallowfullscreen allowfullscreen) not being added to the iframe element.

I went through the sources of both your plugin and included js libs and it seems that those should be set unconditionally, but are nevertheless not.

The reason I am investigating all this is when those attributes are not set, vimeo player disables full-screen option (understandably).

Do you have any experience with this? Should this be videojs's fault, or am I missing something?

Thanks in advance for any help.

**Comment by kubijo** [comment]
I have finally got to the core of the problem.

[Here is the pull request for videojs-vimeo](https://github.com/eXon/videojs-vimeo/commit/0543812e2ebe58ed279d695667b4ae9d38029945)

**Comment by ericamador** [comment]
Thanks for raising this issue, and apologies for the delayed response. It looks like this was indeed a problem with videojs-vimeo, and since the pull request you linked has been merged, I'll go ahead and close this issue. Let us know if you have any other questions.

**Comment by kubijo** [comment]
Well, it is merged indeed. The question stays however, what version is used with your plugin. It seems to me (and I'm prepared to be corrected on this) that there's a fixed version used - one that has this problem.

As I've been investigating this I tried to look for the next version that I could inject onto my instance, but had no luck with that. In the end I've ended patching the script that comes with the plugin.

**Comment by ericamador** [comment]
> It seems to me (and I'm prepared to be corrected on this) that there's a fixed version used - one that has this problem.

Indeed this is the case. Thanks for pointing this out. I'll work on upgrading the version of video.js used. I'll probably just change this to point to their CDN in the template, so that end users can change between versions of video.js at will.

**Comment by kubijo** [comment]
Yeah well that is not ideal too I think. We for example try to limit number of requests to external sources as much as possible and bundle them to be served from our CDNs. Also there is this uncertainty of version being used (if there is some "latest" flag in play).

If I would consider quite environment friendly some settings entry / flag allowing you to specify which version ought to be included. Possibly defaulting to their CDN version, but giving you freedom of opting out and bundlig it to your scripts / serving your copy.

What do you think?

**Comment by ericamador** [comment]
That sounds good to me. Would you be interested in making a pull request for such a feature?

**Comment by kubijo** [comment]
Hi and apologies for the delay.

Since I've never written much in python/django, I'm not much confident in being able to pull something like this off in usable way - however this is how learn in the end.

Hopefully I'll try something this weekend.

**Comment by ericamador** [comment]
No worries. Thanks again for the contribution.

Closed by #6.
